export const philippineLocations = [
    // Metro Manila (NCR)
    { city: "Manila", province: "Metro Manila", region: "NCR", island: "Luzon" },
    { city: "Quezon City", province: "Metro Manila", region: "NCR", island: "Luzon" },
    { city: "Makati", province: "Metro Manila", region: "NCR", island: "Luzon" },
    { city: "Taguig", province: "Metro Manila", region: "NCR", island: "Luzon" },
    { city: "Pasig", province: "Metro Manila", region: "NCR", island: "Luzon" },
    { city: "Caloocan", province: "Metro Manila", region: "NCR", island: "Luzon" },
    { city: "Mandaluyong", province: "Metro Manila", region: "NCR", island: "Luzon" },
    { city: "Pasay", province: "Metro Manila", region: "NCR", island: "Luzon" },
    { city: "Marikina", province: "Metro Manila", region: "NCR", island: "Luzon" },
    { city: "Muntinlupa", province: "Metro Manila", region: "NCR", island: "Luzon" },
    { city: "Las Piñas", province: "Metro Manila", region: "NCR", island: "Luzon" },
    { city: "Parañaque", province: "Metro Manila", region: "NCR", island: "Luzon" },
    { city: "Valenzuela", province: "Metro Manila", region: "NCR", island: "Luzon" },
    { city: "Malabon", province: "Metro Manila", region: "NCR", island: "Luzon" },
    { city: "Navotas", province: "Metro Manila", region: "NCR", island: "Luzon" },
    { city: "San Juan", province: "Metro Manila", region: "NCR", island: "Luzon" },
    { city: "Pateros", province: "Metro Manila", region: "NCR", island: "Luzon" },

    // CALABARZON
    { city: "Antipolo", province: "Rizal", region: "CALABARZON", island: "Luzon" },
    { city: "Cainta", province: "Rizal", region: "CALABARZON", island: "Luzon" },
    { city: "Taytay", province: "Rizal", region: "CALABARZON", island: "Luzon" },
    { city: "Binangonan", province: "Rizal", region: "CALABARZON", island: "Luzon" },
    { city: "San Mateo", province: "Rizal", region: "CALABARZON", island: "Luzon" },
    { city: "Rodriguez", province: "Rizal", region: "CALABARZON", island: "Luzon" },
    { city: "Bacoor", province: "Cavite", region: "CALABARZON", island: "Luzon" },
    { city: "Imus", province: "Cavite", region: "CALABARZON", island: "Luzon" },
    { city: "Dasmariñas", province: "Cavite", region: "CALABARZON", island: "Luzon" },
    { city: "General Trias", province: "Cavite", region: "CALABARZON", island: "Luzon" },
    { city: "Silang", province: "Cavite", region: "CALABARZON", island: "Luzon" },
    { city: "Trece Martires", province: "Cavite", region: "CALABARZON", island: "Luzon" },
    { city: "Calamba", province: "Laguna", region: "CALABARZON", island: "Luzon" },
    { city: "Santa Rosa", province: "Laguna", region: "CALABARZON", island: "Luzon" },
    { city: "Biñan", province: "Laguna", region: "CALABARZON", island: "Luzon" },
    { city: "San Pedro", province: "Laguna", region: "CALABARZON", island: "Luzon" },
    { city: "Cabuyao", province: "Laguna", region: "CALABARZON", island: "Luzon" },
    { city: "Batangas City", province: "Batangas", region: "CALABARZON", island: "Luzon" },
    { city: "Lipa", province: "Batangas", region: "CALABARZON", island: "Luzon" },
    { city: "Tanauan", province: "Batangas", region: "CALABARZON", island: "Luzon" },
    { city: "Lucena", province: "Quezon", region: "CALABARZON", island: "Luzon" },
    { city: "Tanay", province: "Rizal", region: "CALABARZON", island: "Luzon" },

    // Central Luzon
    { city: "San Fernando", province: "Pampanga", region: "Central Luzon", island: "Luzon" },
    { city: "Angeles", province: "Pampanga", region: "Central Luzon", island: "Luzon" },
    { city: "Mabalacat", province: "Pampanga", region: "Central Luzon", island: "Luzon" },
    { city: "Malolos", province: "Bulacan", region: "Central Luzon", island: "Luzon" },
    { city: "Meycauayan", province: "Bulacan", region: "Central Luzon", island: "Luzon" },
    { city: "Santa Maria", province: "Bulacan", region: "Central Luzon", island: "Luzon" },
    { city: "Baliuag", province: "Bulacan", region: "Central Luzon", island: "Luzon" },
    { city: "Tarlac City", province: "Tarlac", region: "Central Luzon", island: "Luzon" },
    { city: "Cabanatuan", province: "Nueva Ecija", region: "Central Luzon", island: "Luzon" },
    { city: "Palayan", province: "Nueva Ecija", region: "Central Luzon", island: "Luzon" },
    { city: "Olongapo", province: "Zambales", region: "Central Luzon", island: "Luzon" },

    // Visayas
    { city: "Cebu City", province: "Cebu", region: "Visayas", island: "Visayas" },
    { city: "Mandaue", province: "Cebu", region: "Visayas", island: "Visayas" },
    { city: "Lapu-Lapu", province: "Cebu", region: "Visayas", island: "Visayas" },
    { city: "Talisay", province: "Cebu", region: "Visayas", island: "Visayas" },
    { city: "Iloilo City", province: "Iloilo", region: "Visayas", island: "Visayas" },
    { city: "Bacolod", province: "Negros Occidental", region: "Visayas", island: "Visayas" },
    { city: "Tacloban", province: "Leyte", region: "Visayas", island: "Visayas" },
    { city: "Ormoc", province: "Leyte", region: "Visayas", island: "Visayas" },

    // Mindanao
    { city: "Davao City", province: "Davao del Sur", region: "Mindanao", island: "Mindanao" },
    { city: "General Santos", province: "South Cotabato", region: "Mindanao", island: "Mindanao" },
    { city: "Zamboanga City", province: "Zamboanga del Sur", region: "Mindanao", island: "Mindanao" },
    { city: "Cagayan de Oro", province: "Misamis Oriental", region: "Mindanao", island: "Mindanao" },
    { city: "Butuan", province: "Agusan del Norte", region: "Mindanao", island: "Mindanao" },
    { city: "Cotabato City", province: "Maguindanao", region: "Mindanao", island: "Mindanao" },

    //others
    { city: "Biringan City", province: "Unknown", region: "Mindanao", island: "Mindanao" },
];